ExamenCarlota11022021/Models/Cesta.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ExamenCarlota11022021.Models
{
    public class Cesta
    {
        public int IdPelicula { get; set; }
        public int Precio { get; set; }
        
        public Cesta(int idpelicula, int precio)
        {
            this.IdPelicula = idpelicula;
            this.Precio = precio;
        }
        public Cesta() : base() { }
    }
}

ExamenCarlota11022021/Models/Genero.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace ExamenCarlota11022021.Models
{
    [Table("Generos")]
    public class Genero
    {
        [Key]
        [Column("idgenero")]
        public int Id { get; set; }
        [Column("genero")]
        public String Generos { get; set; }
    }
}

ExamenCarlota11022021/Models/Pelicula.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace ExamenCarlota11022021.Models
{
    [Table("Peliculas")]
    public class Pelicula
    {
        [Key]
        [Column("Idpelicula")]
        public int Id { get; set; }
        [Column("IdDistribuidor")]
        public int Iddistribuidor { get; set; }
        [Column("idgenero")]
        public int Idgenero { get; set; }
        [Column("titulo")]
        public String Titulo { get; set; }
        [Column("argumento")]
        public String Argumento { get; set; }
        [Column("foto")]
        public String Foto { get; set; }
        [Column("fecha_estreno")]
        public DateTime Fechaestreno { get; set; }
        [Column("actores")]
        public String Actores { get; set; }
        [Column("director")]
        public String Director { get; set; }
        [Column("duracion")]
        public int Duracion { get; set; }
        [Column("precio")]
        public int Precio { get; set; }

    }
}

ExamenCarlota11022021/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using ExamenCarlota11022021.Extensions;
using ExamenCarlota11022021.Helpers;
using ExamenCarlota11022021.Models;
using ExamenCarlota11022021.Repositories;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace ExamenCarlota11022021.Controllers
{
    public class HomeController : Controller
    {
        IRepository repo;
        ISession session => HttpContext.Session;
        UploadService uploadService;
        public HomeController(IRepository repo, UploadService uploadService)
        {
            this.repo = repo;
            this.uploadService = uploadService;
        }

        public IActionResult Index()
        {
            session.SetString("algo", "algo");

            //session.SetObject("CESTA", new List<Cesta>());

            String text = session.GetString("algo");



            return View(this.repo.FindAllPelis());
        }
        public IActionResult ListarPelisGenero(int id)
        {
            return View(this.repo.FindPeliByGenero(id));
        }
        public IActionResult DetallePeli(int id)
        {
            return View(this.repo.FindPeliById(id));
        }
        public IActionResult GuardarCesta(int id)
        {

            List<Cesta> listacesta = session.GetObject<List<Cesta>>("CESTA");
            List<Cesta> cestita = new List<Cesta>();
            Cesta cestanueva;
            Cesta cestaantes;

            Pelicula peli = this.repo.FindPeliById(id);

            cestanueva = new Cesta();
            cestanueva.IdPelicula = peli.Id;
            cestanueva.Precio = peli.Precio;
            cestita.Add(cestanueva);

            if (listacesta != null)
            {
                foreach (Cesta c in listacesta)
                {
                    cestaantes = new Cesta();
                    cestaantes.Precio = c.Precio;
                    cestaantes.IdPelicula = c.IdPelicula;
                    if (c.IdPelicula != cestanueva.IdPelicula)
                    {
                        cestita.Add(cestaantes);
                    }
                }
            }
            session.SetObject("CESTA", cestita);
         
            return RedirectToAction("detallepeli", peli);

        }

        public IActionResult VerCesta()
        {
            return View();
        }
        public IActionResult EliminarPeli(int id)
        {
            List<Cesta> listacesta = session.GetObject<List<Cesta>>("CESTA");

            List<Cesta> cestita = new List<Cesta>();

            foreach (Cesta c in listacesta)
            {
             if(c.IdPelicula != id)
                {
                    Cesta cesta = new Cesta();
                    cesta.IdPelicula = c.IdPelicula;
                    cesta.Precio = c.Precio;
                    cestita.Add(cesta);
                }
            }
            session.SetObject("CESTA", cestita);
            return RedirectToAction("vercesta");
        }
        //[HttpPost]
        //public IActionResult VerCesta(int[] id)
        //{
        //    List<Cesta> listacesta = session.GetObject<List<Cesta>>("CESTA");
        //    List<Cesta> cestita = new List<Cesta>();
        //    Cesta cestanueva;

        //    if (listacesta != null)
        //    {
        //        foreach (Cesta c in listacesta)
        //        {
        //            for (int i = 0; i < id.Length; i++)
        //            {
        //                if (c.IdPelicula == id[i])
        //                {
        //                    cestanueva = new Cesta(c.IdPelicula, c.Precio);
        //                    cestita.Add(cestanueva);
        //                }
        //            }
        //        }
        //    }

        //    session.SetObject("CESTA", cestita);

        //    return View();
        //}
        public IActionResult Comprar()
        {

            return View();
        }

        public IActionResult Modificar(int id)
        {
            return View(this.repo.FindPeliById(id));
        }
        [HttpPost]
        public async Task<IActionResult> Modificar(Pelicula pelicula, IFormFile foto)
        {           
            Pelicula peli= this.repo.FindPeliById(pelicula.Id);

            if(foto != null)
            {
               await this.uploadService.UploadFileAsync(foto, Folders.Images);
                peli.Foto = foto.FileName;
            }
            peli.Precio = pelicula.Precio;
            this.repo.Update(peli);

            return RedirectToAction("detallepeli", peli);
        }
    }
}

ExamenCarlota11022021/Controllers/PeliculasController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ExamenCarlota11022021.Controllers
{
    public class PeliculasController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
   
    }
}

ExamenCarlota11022021/ViewComponents/MenuGenerosViewComponent.cs
using ExamenCarlota11022021.Repositories;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ExamenCarlota11022021.ViewComponents
{
    public class MenuGenerosViewComponent:ViewComponent
    {
        IRepository repository;
        public MenuGenerosViewComponent(IRepository repository)
        {
            this.repository = repository;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View(this.repository.FindAllGeneros());
        }
    }
}

ExamenCarlota11022021/Views/Home/Comprar.cshtml
@{

    List<Cesta> cestita = Context.Session.GetObject<List<Cesta>>("CESTA");
    int cantidad = 0;
    if (cestita != null)
    {
        @foreach (Cesta c in cestita)
        {
            cantidad += c.Precio;
        }
    }

}


<h1>TU COMPRA</h1>

<ul class="list-group">
    @if (cestita != null)
    {
        @foreach (Cesta c in cestita)
        {
            <li class="list-group-item">
                Producto: @c.IdPelicula
            </li>
        }
    }

    
</ul>
<h5 style="color:cornflowerblue">Total: @cantidad €</h5>

ExamenCarlota11022021/Views/Home/DetallePeli.cshtml
@{
    ViewData["Title"] = "DetallePeli";
}
@model Pelicula
<h1>DetallePeli</h1>

<div class="card">
    <img src="~/images/@Model.Foto" style="width:150px" />
    <div class="card-body">
        <h2>@Model.Titulo</h2>
        
        <h5>@Model.Actores </h5>
        <p>@Model.Argumento</p>
    </div>
    <div class="card-footer">
        <a asp-action="Guardarcesta" asp-controller="Home" asp-route-id="@Model.Id">
            Comprar
        </a>
        <a asp-action="Index" asp-controller="Home">
            Volver
        </a>
        <a asp-action="Modificar" asp-controller="Home" asp-route-id="@Model.Id">
            modificar
        </a>
    </div>

</div>

ExamenCarlota11022021/Views/Home/Index.cshtml
@model List<Pelicula>

<h1>ListarPelis</h1>

<table>
    <thead>
        <tr>
            <th>TITULO</th>
            <th>PRECIO</th>
            <th>CARTEL</th>
            <th>--</th>
        </tr>
    </thead>
    <tbody>
        @foreach (Pelicula p in Model)
        {
            <tr>
                <td>@p.Titulo</td>
                <td>@p.Precio</td>
                <td>
                    <img src="~/images/@p.Foto" style="width:150px;" />
                </td>
                <td> <a class="btn btn-info" asp-action="DetallePeli" asp-controller="Home" asp-route-id="@p.Id">Ver Detalles</a> </td>
            </tr>
        }

    </tbody>
</table>

ExamenCarlota11022021/Views/Home/ListarPelisGenero.cshtml
@model List<Pelicula>

<h1>ListarPelis</h1>

<table>
    <thead>
        <tr>
            <th>TITULO</th>
            <th>PRECIO</th>
            <th>CARTEL</th>
            <th>--</th>
        </tr>
    </thead>
    <tbody>
        @foreach (Pelicula p in Model)
        {
        <tr>
            <td>@p.Titulo</td>
            <td>@p.Precio</td>
            <td>
                <img src="~/images/@p.Foto" style="width:150px" />
            </td>
            <td> <a class="btn btn-info" asp-action="DetallePeli" asp-controller="Home" asp-route-id="@p.Id">Ver Detalles</a> </td>
        </tr>
        }

    </tbody>
</table>

ExamenCarlota11022021/Views/Home/Modificar.cshtml
@model Pelicula

<form method="post" enctype="multipart/form-data">
    <label>Precio</label>
    <input value="@Model.Precio" name="precio" type="text" />
    <label>Imagen</label>
    <input name="foto" type="file" />
    <button class="btn btn-danger" type="submit">modificar</button>
</form>

ExamenCarlota11022021/Views/Home/VerCesta.cshtml
@{

    List<Cesta> cestita = Context.Session.GetObject<List<Cesta>>("CESTA");

}

<h1>VerCesta</h1>

    <ul class="list-group">
        @if (cestita != null)
        {
            @foreach (Cesta c in cestita)
            {
                <li class="list-group-item"> Producto: @c.IdPelicula  <a asp-controller="Home" asp-action="EliminarPeli" asp-route-id="@c.IdPelicula">eliminar</a>   </li>
            }
        }
        
    </ul>
    <a asp-action="comprar" asp-controller="home"  class="btn btn-success">comprar</a>

ExamenCarlota11022021/Views/Shared/Components/MenuGeneros/Default.cshtml
@model List<Genero>
@{
    List<Cesta> cestita = Context.Session.GetObject<List<Cesta>>("CESTA");
    int cantidad = 0;
    if (cestita != null)
    {
        @foreach (Cesta c in cestita)
        {
            cantidad += c.Precio;
        }
    }


}
<div class="col">
    <h3>Generos</h3>
    @foreach (Genero d in Model)
    {
        <a class="dropdown-item"
           asp-controller="Home"
           asp-action="ListarPelisGenero" asp-route-id="@d.Id">
            @d.Generos
        </a>
    }

</div>

<div class="col">
    <h3 style="color:rebeccapurple">Compras</h3>

    @if (cestita != null)
    {

        <ul class="list-group">

            <li class="list-group-item">Compras: @cestita.AsEnumerable().Count()  </li>

        </ul>
    }

    <h5 style="color:cornflowerblue">Total: @cantidad</h5>

</div>
<div>
    <a class="dropdown-item"
       asp-controller="Home"
       asp-action="vercesta">
        ver cesta
    </a>
</div>

ExamenCarlota11022021/Views/Shared/_Layout.cshtml
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="/docs/4.0/assets/img/favicons/favicon.ico">

    <title>@ViewData["Title"]</title>
    <!-- Bootstrap core CSS -->
    <link href="~/css/bootstrap.min.css" rel="stylesheet" />

    <!-- Custom styles for this template -->
    <link href="~/css/jumbotron.css" rel="stylesheet" />
</head>
<body>

    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarsExampleDefault">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Link</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link disabled" href="#">Disabled</a>
                </li>
               

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Ejemplos</a>
                    <div class="dropdown-menu" aria-labelledby="dropdown01">
                        <a class="dropdown-item"
                           asp-controller="Home"
                           asp-action="Index">Casa</a>
                    </div>
                </li>
            </ul>
            <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>
    </nav>

    <main role="main">

        <!-- Main jumbotron for a primary marketing message or call to action -->
        <div class="jumbotron">
            <div class="container">
                <div class="row d-flex flex-row">
                    <div class="col">
                    @await Component.InvokeAsync("MenuGeneros")
                    </div>
                    <div class="col">@RenderBody()</div>
                    
                </div>
                
            </div>
        </div>

        <div class="container">
            
            <hr>

        </div> <!-- /container -->

    </main>

    <footer class="container">
        <p>&copy; Company 2021</p>
    </footer>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="~/js/jquery-3.5.1.min.js"></script>
    <script src="~/js/popper.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    @RenderSection("scripts", false)
</body>
</html>